version: '3'
services:
  dev:
    image: meganetaaan/moddable-esp32
    privileged: true
    network_mode: host
    volumes:
      - /dev:/dev
      - ./:/workspace
      - ./tmp:/root/Projects/moddable/build/tmp
      - /workspace/tmp/
    environment:
      - DISPLAY
    command: /bin/bash
